- name: Install logrotate
  apt: pkg=logrotate
  sudo: yes


- name: Push logrotate main config file
  template:
    src=logrotate.conf.j2
    dest=/etc/logrotate.conf
  sudo: yes
  notify: logrotate-apply

- name: Push logrotate specific config file
  template:
    src=logrotate.d/apache2.j2
    dest=/etc/logrotate.d/apache2
  sudo: yes
  notify: logrotate-apply
